sof_api:
    resource: "@SofApiBundle/Controller/"
    type:     annotation
    prefix:   /

user_auth:
  pattern: /authenticate

user_logout:
  pattern: /user_logout

homepage:
    pattern:   /
    defaults:  { _controller: SofApiBundle:Login:index }

