security:
    encoders:
        Sof\ApiBundle\Entity\User:
            algorithm: md5
            encode_as_base64: false
            iterations: 1

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
#        in_memory:
#            memory:
#                users:
#                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
#                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
        user_db:
            entity: { class: Sof\ApiBundle\Entity\User }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/(login$|login\.css$)
            security: false

        secured_area:
            pattern:    ^/
            form_login:
                use_referer: true
                always_use_default_target_path: true
                check_path: /authenticate
                login_path: /login
                default_target_path: /Common_Index
                username_parameter: login_username
                password_parameter: login_password
            logout:
                path:   /user_logout
                target: /login

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
