<?php

namespace Sof\ApiBundle\Entity;

use Sof\ApiBundle\Lib\Config;

use Sof\ApiBundle\Lib\SofUtil;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Security\Core\Exception\UsernameNotFoundException;
use Symfony\Component\Security\Core\Exception\UnsupportedUserException;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NoResultException;

/**
 * CustomerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerRepository extends BaseRepository
{
    public function getData() {
        $query = $this->querySimpleEntities(array('selects' => array('id', 'name')));
        $query->innerJoin(self::ENTITY_BUNDLE . ":Invoice", 'invoice', 'WITH', "entity.id = invoice.subject");

        return SofUtil::formatScalarArray($query->getQuery()->getScalarResult());
    }
}
