<?php

namespace Sof\ApiBundle\Entity;

use Sof\ApiBundle\Entity\ValueConst\InvoiceConst;
use Sof\ApiBundle\Lib\SofUtil;

/**
 * CustomerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerRepository extends BaseRepository
{
    /**
     * @return Array
     *
     * @author HieuNLD 2014/11/13
     */
    public function getData() {
        $query = $this->querySimpleEntities(array(
            'selects' => array('id', 'name'),
            'groupBy' => array('id')
        ));
        $query->innerJoin(self::ENTITY_BUNDLE . ":Invoice", 'invoice', 'WITH', "entity.id = invoice.subject AND invoice.invoiceType = " . InvoiceConst::INVOICE_TYPE_2);

        return SofUtil::formatScalarArray($query->getQuery()->getScalarResult());
    }
}
