<?php

namespace Sof\ApiBundle\Entity;

use Sof\ApiBundle\Lib\SofUtil;

/**
 * DriverRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DriverInvoiceRepository extends BaseRepository
{

    /**
     * @param $driverId
     * @return Array
     *
     * @author HieuNLD 2014/11/13
     */
    public function getData_Delivery($driverId) {
        $query = $this->querySimpleEntities(array(
                'selects' => array('id', 'invoiceId', 'driverId'),
                'conditions' => array('driverId' => $driverId)
            ));

        $query->addSelect('i.invoiceNumber,i.createInvoiceDate,i.address,i.phoneNumber');
        $query->addSelect('c.name AS customerName');

        $query->leftJoin(self::ENTITY_BUNDLE . ":Invoice", 'i', 'WITH', "entity.invoiceId = i.id");
        $query->leftJoin(self::ENTITY_BUNDLE . ":Customer", 'c', 'WITH', "i.subject = c.id");

        return SofUtil::formatScalarArray($query->getQuery()->getScalarResult());
    }
}
